### ISSUE TITLE
bus error on tegras with optimized builds

### ISSUE THREAD

**Issue by dhperkins** [Aqueti/atl#53]
this has popped up a two or three times now. 
SIGBUS is the terminal outpu
dmesg says alignment error
in gdb it seems to happen in base container. 

will try to reproduce tomorrow and get actual output and backtrace

**Comment by russell-taylor** [comment]
This sounds like a result of trying to treat classes/structs as blocks of bytes rather than having proper marshall/unmarshall methods.  Bytes are 8-bit aligned, whereas 16-bit and 32-bit values (and 64-bit doubles).  When you allocate a class or structure, C++ guarantees to align all of its elements.  When you allocate a byte array, it only guarantees to align to 8-bit boundaries.  We handle this in VRPN for single elements by allocating a pointer to the type we want to convert to and then type-casting that back into a char buffer, so that the result is aligned.

There are other dragons waiting with this approach, like class/structure packing order differing on different architectures (C++ does not guarantee an ordering) and copying of virtual function pointers to a thread/process/restoration where they don't make sense.

**Comment by sfeller** [comment]
Russell is correct in that there are some subtleties in this approach as we move between compilers and hardware components. While it is critical we understand this risk, it is also important that we maintain the data in contiguous memory especially at the hardware interface. I'm fairly sure the initial issue was due to breaking byte alignment constraints by changing the magic number in the metadata to 6 bytes instead of 8 (probably my bad). The longer term solution will be to manage the metadata as C code which can be linked in and handle accessors through the Container classes. This is implemented in the C branch, but I haven't tested it thoroughly yet.

**Comment by dhperkins** [comment]
build type RelWithDebInfo
gdb: 

Program received signal SIGBUS, Bus error.
[Switching to Thread 0xf4dff450 (LWP 31452)]
atl::HContainer::add (this=0xfffeecfc, container=...) at /home/ubuntu/build/aci/atl-prefix/src/atl/Buffer/HContainer.cpp:114
114	      contMeta->m_offset += head;
(gdb) bt
#0  atl::HContainer::add (this=0xfffeecfc, container=...) at /home/ubuntu/build/aci/atl-prefix/src/atl/Buffer/HContainer.cpp:114
#1  0x00057eac in MemoryManager::addObject (this=0xfffeece0, container=...) at /home/ubuntu/src/aci/src/MemoryController/MemoryManager.cpp:133
#2  0x0004a958 in MemoryController::mainLoop (this=0xfffeeca0) at /home/ubuntu/src/aci/src/MemoryController/MemoryController.cpp:48
#3  0x000a57c4 in atl::Thread::Execute (this=0xfffeeca0) at /home/ubuntu/build/aci/atl-prefix/src/atl/Thread/Thread.cpp:95
#4  0xf7312854 in ?? () from /usr/lib/arm-linux-gnueabihf/libstdc++.so.6

**Comment by dhperkins** [comment]
dmesg:
[ 1317.749356] Unhandled fault: alignment fault (0x92000021) at 0x0000000095185ed9

**Comment by dhperkins** [comment]
changed default allocation block size to 8 bytes in various container allocators. was previously 1 byte.
